export const EVENT_STRINGS = {
    title: "Historia clínica",
    description: "Consulta los hechos registrados, sin modificar tu historia.",
    empty: "Todavía no hay hechos registrados en tu historia clínica.",
    unavailable: "Este hecho ya no está disponible.",
    failure: "No pudimos cargar tu historia clínica.",
    retry: "Reintentar",
    back: "Volver a la historia",
    detail: "Detalle del hecho",
    filters: "Filtrar y ordenar",
    allTypes: "Todos los tipos",
    type: "Tipo",
    from: "Desde",
    to: "Hasta",
    order: "Ordenar por",
    recordDate: "Fecha de registro",
    occurrenceDate: "Fecha de ocurrencia",
    occurrence: "Ocurrió",
    recorded: "Registrado",
    approximate: "Fecha aproximada",
    unknownDate: "Fecha no determinada",
    types: {
        diagnosis: "Diagnóstico",
        medication: "Medicación",
        measurement: "Medición",
        note: "Nota",
    },
} as const;